package com.example.demo.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.demo.TimeConverter;
import java.time.LocalDateTime;

import com.example.demo.entity.Notification;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTIFICATION".
*/
public class NotificationDao extends AbstractDao<Notification, Integer> {

    public static final String TABLENAME = "NOTIFICATION";

    /**
     * Properties of entity Notification.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, int.class, "id", true, "ID");
        public final static Property SenderId = new Property(1, String.class, "senderId", false, "SENDER_ID");
        public final static Property ReceiverId = new Property(2, String.class, "receiverId", false, "RECEIVER_ID");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Time = new Property(5, long.class, "time", false, "TIME");
    }

    private final TimeConverter timeConverter = new TimeConverter();

    public NotificationDao(DaoConfig config) {
        super(config);
    }
    
    public NotificationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTIFICATION\" (" + //
                "\"ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SENDER_ID\" TEXT NOT NULL ," + // 1: senderId
                "\"RECEIVER_ID\" TEXT NOT NULL ," + // 2: receiverId
                "\"TITLE\" TEXT NOT NULL ," + // 3: title
                "\"CONTENT\" TEXT NOT NULL ," + // 4: content
                "\"TIME\" INTEGER NOT NULL );"); // 5: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTIFICATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Notification entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getSenderId());
        stmt.bindString(3, entity.getReceiverId());
        stmt.bindString(4, entity.getTitle());
        stmt.bindString(5, entity.getContent());
        stmt.bindLong(6, timeConverter.convertToDatabaseValue(entity.getTime()));
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Notification entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getSenderId());
        stmt.bindString(3, entity.getReceiverId());
        stmt.bindString(4, entity.getTitle());
        stmt.bindString(5, entity.getContent());
        stmt.bindLong(6, timeConverter.convertToDatabaseValue(entity.getTime()));
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public Notification readEntity(Cursor cursor, int offset) {
        Notification entity = new Notification( //
            cursor.getInt(offset + 0), // id
            cursor.getString(offset + 1), // senderId
            cursor.getString(offset + 2), // receiverId
            cursor.getString(offset + 3), // title
            cursor.getString(offset + 4), // content
            timeConverter.convertToEntityProperty(cursor.getLong(offset + 5)) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Notification entity, int offset) {
        entity.setId(cursor.getInt(offset + 0));
        entity.setSenderId(cursor.getString(offset + 1));
        entity.setReceiverId(cursor.getString(offset + 2));
        entity.setTitle(cursor.getString(offset + 3));
        entity.setContent(cursor.getString(offset + 4));
        entity.setTime(timeConverter.convertToEntityProperty(cursor.getLong(offset + 5)));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(Notification entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public Integer getKey(Notification entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Notification entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
